version: '3.5'

services:
  postgres:
    container_name: postgres_container
    restart: always
    image: postgres
    environment:
      POSTGRES_DB: example_db
      POSTGRES_USER: example_user
      POSTGRES_PASSWORD: example_password
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080